MAX_TOKENS = 512
CATALOG_ID = "b1gg73sjtlolmm1ght1n"
API_KEY_GPT = "AQVN2fUQU-GIqOtWsKADWY1iyzPViNKmcMFJCyLa"
API_KEY_TTS = 'AQVNyOIi4pxzxS4upHvl2j49b8AwYuLpMWDTYvaI'
API_KEY_SST = "AQVNw0Zfqj1KTD-N7arqrYpfcCDkqlFs3MKeCrbW"